apiVersion: batch/v1
kind: CronJob
metadata:
  name: feast-materialize
  namespace: crypto
spec:
  schedule: "*/1 * * * *"    # every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: feast-materialize
              image: YOUR_IMAGE_WITH_FEAST_AND_REPO   # we will build this next
              command:
                ["feast", "materialize-incremental", "$(date -Iseconds)"]
              env:
                - name: FEAST_REPO_PATH
                  value: "/repo/feature_repo"
          restartPolicy: OnFailure
